parameters:
#    intaro_user.example.class: Intaro\UserBundle\Example

services:
#    intaro_user.example:
#        class: %intaro_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
